novel_weixin_web/src/main/java/com/potato369/novel/dto/OrderDTO.java
package com.potato369.novel.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.potato369.novel.basic.dataobject.OrderDetail;
import com.potato369.novel.basic.enums.OrderStatusEnum;
import com.potato369.novel.basic.enums.PayStatusEnum;
import com.potato369.novel.utils.EnumUtil;
import com.potato369.novel.utils.serializer.Date2LongSerializer;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
/**
 * <pre>
 * @PackageName com.potato369.novel.dto
 * @ClassName OrderDTO
 * @Desc 订单信息DTO
 * @WebSite https://www.potato369.com
 * @Author Jack
 * @Date 2019/01/08 17:59
 * @CreateBy IntellJ IDEA 2018.3.2
 * @Copyright Copyright (c) 2016 ~ 2020 版权所有 (C) 土豆互联科技(深圳)有限公司 https://www.potato369.com All Rights Reserved。
 * </pre>
 */
@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
public class OrderDTO {

    /**
     * <pre>
     * @Field orderId：订单编号
     * </pre>
     */
    private String orderId;

    /**
     * <pre>
     * @Field orderName：订单名称
     * </pre>
     */
    private String orderName;

    /**
     * <pre>
     * @Field buyerName：买家名字
     * </pre>
     */
    private String buyerName;

    /**
     * <pre>
     * @Field buyerAddress：买家地址
     * </pre>
     */
    private String buyerAddress;

    /**
     * <pre>
     * @Field buyerOpenid：买家微信openid
     * </pre>
     */
    private String buyerOpenid;

    /**
     * <pre>
     * @Field orderAmount：订单总金额
     * </pre>
     */
    private BigDecimal orderAmount;

    /**
     * <pre>
     * @Field orderStatus：订单状态，默认是新下单
     * </pre>
     */
    private Integer orderStatus;

    /**
     * <pre>
     * @Field payStatus：支付状态，默认0为未支付
     * </pre>
     */
    private Integer payStatus;

    /**
     * <pre>
     * @Field createTime：创建时间
     * </pre>
     */
    @JsonSerialize(using = Date2LongSerializer.class)
    private Date createTime;

    /**
     * <pre>
     * @Field updateTime：更新时间
     * </pre>
     */
    @JsonSerialize(using = Date2LongSerializer.class)
    private Date updateTime;

    @Transient
    private List<OrderDetail> orderDetailList;

    @JsonIgnore
    public OrderStatusEnum getOrderStatusEnum(){
        return EnumUtil.getByCode(orderStatus, OrderStatusEnum.class);
    }

    @JsonIgnore
    public PayStatusEnum getPayStatusEnum(){
        return EnumUtil.getByCode(payStatus, PayStatusEnum.class);
    }

    /**
     * <pre>
     * @Field cip：买家微信客户端ip
     * </pre>
     */
    private String cip;

    /**
     * <pre>
     * @Field fingerPrint：浏览器指纹
     * </pre>
     */
    private String fingerPrint;

    /**
     * <pre>
     * @Field jsonSceneInfo：json格式场景信息字符串
     * </pre>
     */
    private String jsonSceneInfo;
}

novel_weixin_web/src/main/resources/templates/order/detail.ftl
<html>
    <#include "../common/header.ftl">
<body>
    <div id="wrapper" class="toggled">
        <#--边栏 sidebar-->
        <#include "../common/nav.ftl">
        <#--主体内容区域 content-->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row clearfix">
                <#--订单数据-->
                    <div class="col-md-8 column">
                        <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th style="text-align: center">
                                    订单id
                                </th>
                                <th style="text-align: center">
                                    订单总金额
                                </th>
                                <th style="text-align: center">
                                    订单状态
                                </th>
                                <th style="text-align: center">
                                    支付状态
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="success" style="text-align: center">
                                <td>
                                ${orderDTO.orderId}
                                </td>
                                <td>
                                ${orderDTO.orderAmount}
                                </td>
                                <td>
                                ${orderDTO.orderStatusEnum.message}
                                </td>
                                <td>
                                ${orderDTO.payStatusEnum.getMessage()}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <#--订单详情表数据-->
                    <div class="col-md-12 column">
                        <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th style="text-align: center">商品id</th>
                                <th style="text-align: center">商品名称</th>
                                <th style="text-align: center">价格</th>
                                <th style="text-align: center">数量</th>
                                <th style="text-align: center">总额</th>
                            </tr>
                            </thead>
                            <tbody>
                                <#list orderDTO.orderDetailList as orderDetail>
                                    <tr class="warning" style="text-align: center">
                                        <td>
                                            ${orderDetail.productId}
                                        </td>
                                        <td>
                                            ${orderDetail.productName}
                                        </td>
                                        <td>
                                            ${orderDetail.productPrice}
                                        </td>
                                        <td>
                                            ${orderDetail.productQuantity}
                                        </td>
                                        <td>
                                            ${orderDetail.productPrice * orderDetail.productQuantity}
                                        </td>
                                    </tr>
                                </#list>
                            </tbody>
                        </table>
                    </div>
                    <#--按钮操作-->
                    <div class="col-md-12 column">
                        <#if orderDTO.getOrderStatusEnum().code == 0>
                            <a type="button" class="btn btn-primary btn-default active" href="/novel/order/finish?orderId=${orderDTO.orderId}">完结订单</a>
                            <a type="button" class="btn btn-default active btn-danger" href="/novel/order/cancel?orderId=${orderDTO.orderId}">取消订单</a>
                        </#if>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

novel_weixin_web/src/main/resources/templates/order/list.ftl
<html>
    <#include "../common/header.ftl">
    <body>
        <div id="wrapper" class="toggled">
            <#--边栏 sidebar-->
            <#include "../common/nav.ftl">
            <#--主体内容区域 content-->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row clearfix">
                        <!--表格数据-->
                        <div class="col-md-12 column">
                            <table class="table table-bordered table-hover table-condensed">
                                <thead>
                                <tr>
                                    <th style="text-align: center">订单id</th>
                                    <th style="text-align: center">订单名称</th>
                                    <th style="text-align: center">买家姓名</th>
                                    <th style="text-align: center">微信openid</th>
                                    <th style="text-align: center">地址</th>
                                    <th style="text-align: center">金额</th>
                                    <th style="text-align: center">订单状态</th>
                                    <th style="text-align: center">支付状态</th>
                                    <th style="text-align: center">创建时间</th>
                                    <th style="text-align: center">修改时间</th>
                                    <th colspan="2" style="text-align: center">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <#list orderDTOPage.content as orderDTO>
                                        <tr class="success">
                                            <td>${orderDTO.orderId}</td>
                                            <td>${orderDTO.orderName}</td>
                                            <td>${orderDTO.buyerName}</td>
                                            <td>${orderDTO.buyerOpenid}</td>
                                            <td>${orderDTO.buyerAddress}</td>
                                            <td>${orderDTO.orderAmount}</td>
                                            <td>${orderDTO.getOrderStatusEnum().message}</td>
                                            <td>${orderDTO.getPayStatusEnum().message}</td>
                                            <td>${orderDTO.createTime}</td>
                                            <td>${orderDTO.updateTime}</td>
                                            <td><a href="/novel/order/detail?orderId=${orderDTO.orderId}">详情</a></td>
                                            <td>
                                                <#if orderDTO.getOrderStatusEnum().code == 0>
                                                    <a href="/novel/order/cancel?orderId=${orderDTO.orderId}">取消</a>
                                                </#if>
                                            </td>
                                        </tr>
                                    </#list>
                                </tbody>
                            </table>
                        </div>
                        <!--分页-->
                        <div class="col-md-12 column">
                            <ul class="pagination pull-right">
		                        <#if currentPage lte 1>
		                            <li class="disabled"><a href="#">上一页</a></li>
		                        <#else>
		                            <li><a href="/novel/order/list?page=${currentPage - 1}&size=${size}">上一页</a></li>
		                        </#if>
			                    <#if orderDTOPage.totalPages gt 0>
                                    <#list 1..orderDTOPage.totalPages as index>
                                        <#if currentPage == index>
			                            <li class="disabled"><a href="#">${index}</a></li>
                                        <#else>
			                            <li><a href="/novel/order/list?page=${index}&size=${size}">${index}</a></li>
                                        </#if>
                                    </#list>
                                <#else>
                                    <li class="disabled"><a href="#">${currentPage}</a></li>
			                    </#if>
		                        <#if currentPage gte orderDTOPage.totalPages>
		                            <li class="disabled"><a href="#">下一页</a></li>
		                        <#else>
		                            <li><a href="/novel/order/list?page=${currentPage + 1}&size=${size}">下一页</a></li>
		                        </#if>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <#--弹窗-->
        <div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button onclick="closePopWindow();" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">【温馨提醒】</h4>
                    </div>
                    <div class="modal-body">您有新的楼兰书城书币购买订单，订单号：<span id="message"></span>，请点击“查看新的订单”按钮，查看新的订单信息！！！</div>
                    <div class="modal-footer">
                        <button onclick="closePopWindow();" type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button onclick="seeNewOrder();" type="button" class="btn btn-primary">查看新的订单</button>
                    </div>
                </div>
            </div>
        </div>

        <#--播放音乐-->
        <audio id="notice" loop="loop"><source src="/novel/mp3/song.mp3" type="audio/mpeg" /></audio>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <script>
            var webSocket = null;
            if ("WebSocket" in window) {
                //开发环境（dev） ：
                webSocket = new WebSocket("wss://potato369.mynatapp.cc/novel/webSocket");
                //测试环境（test）：webSocket = new WebSocket("wss://potato369.mynatapp.cc/novel/webSocket");
                //生产环境（prod）：webSocket = new WebSocket("wss://www.potato369.com/novel/webSocket");
            } else {
                alert("浏览器不支持WebSocket！！！");
            }
            webSocket.onopen = function (event) {
                console.log("与服务器端WebSocket建立连接！！！", event.data);
            }
            webSocket.onclose = function (event) {
                console.log("服务器端WebSocket关闭连接！！！", event.data);
            }
            webSocket.onmessage = function (event) {
                console.log("收到服务器端WebSocket广播消息：", event.data);
                // 弹窗提醒，同时播放音乐
                $("#message").html('<label style="color: red; font-weight: bold;">'+event.data+'</label>');
                $('#myModal').modal('show');
                document.getElementById("notice").play();
            }
            webSocket.onerror = function () {
                console.log("与服务器端WebSocket通讯发生错误！！！");
            }
            window.onbeforeunload = function (event) {
                console.log("离开（刷新或关闭）当前页面，关闭与服务器端WebSocket连接！！！", event.data);
                webSocket.close();
            }
            function closePopWindow() {
            	document.getElementById('notice').pause();
            	window.location.reload();
            }
            function seeNewOrder() {
                var orderId = $("#message").text().trim();
                document.getElementById('notice').pause();
                window.location.href='/novel/order/detail?orderId='+ orderId;
            }
        </script>
    </body>
</html>